# 使用例子，请根据实际情况修改

description = "HelixFold3 Prediction Pipeline"
[arguments]
# TODO mode = { required = false, default = "single", choices = ["single", "batch"], help = "execution mode: single task or batch tasks" }
job_name = { required = false, default = "complex", help = "job name for the prediction task" }
protein = { required = false, help = "path to protein sequences FASTA file" }
dna = { required = false, help = "path to DNA sequences FASTA file" }
rna = { required = false, help = "path to RNA sequences FASTA file" }
ligand = { required = false, help = "path to ligand entries file" }
ion = { required = false, help = "ion CCD code (MG/ZN/CL/CA/NA/MN/MN3/K/FE/FE2/CU/CU1/CU3/CO)" }
recycle = { type = "int", default = 10, choices = [10, 20, 50, 100], help = "recycle parameter for model inference (10/20/50/100)" }
ensemble = { type = "int", default = 5, choices = [1, 5, 10, 100], help = "ensemble parameter for model inference (1/5/10/100)" }
