# 使用例子，请根据实际情况修改

description = "HelixFold3 Prediction Pipeline"
[arguments]
protein = { required = false, help = "protein sequences in FASTA format" }
dna = { required = false, help = "DNA sequences in FASTA format" }
rna = { required = false, help = "RNA sequences in FASTA format" }
ligand = { required = false, help = "ligand and ion entries, one per line" }
topN = { type = "int", default = 5, help = "topN structure for ranked output" }
recycle = { type = "int", default = 10, help = "recycle parameter for model inference" }
ensemble = { type = "int", default = 1, help = "ensemble parameter for model inference" }
