#!/bin/bash

# 设置执行路径
SCRIPT_PATH="/data/PRG/tools/helixfold3/apps/helixfold3_wemol/src/py_script_template/__main__.py"

# 小型蛋白质测试
echo "Running small protein test..."
python $SCRIPT_PATH --job_name pro_300AA --protein ">pro_300AA.A
GPVIRQGPVNQTVAVDGTFVLSCVATGSPVPTILWRKDGVLVSTQDSRIKQLENGVLQIRYAKLGDTGRYTCIASTPSGEATWSAYIEVQ
>pro_300AA.B
EVQLVESGGGVVQPGGSLKLSCAASGFTFSTYDMSWVRQTPDKRLELVATINSNGGSTYYPDSV
KGRFTSSRDNAKNILYLQMSSLKSEDTAMYYCAREALLRPPYYALDYWGQGTSVTVS
>pro_300AA.C
LDIQMTQSPASLSASVGETVTITCGASENIYGALTWYQRKQGKSPQLLIYGAINLADDKSSRFSGSGSGRQYSLKISSLHPDDVATYYCQNVLSTPFTFGSGTKLEIK"

# # 中型蛋白质测试
# echo "Running medium protein test..."
# python $SCRIPT_PATH --job_name pro_600AA --protein ">pro_600AA.A
# VSGITALTVVVGTVIGAGIFFKPTAVYGAAGAPGLGLLAWFVAGIITIAGGLTVAEIGTIYPQTGGMMIYLEKVYGRWLGFLVGWAQMVIYYPANIAALAIIFATQFVNLFALSDSTIVPTAILTSIFLMGVNFLGTKYSGWIQTLATILKLIPLVVIIVAGLLYPGGGVIRLVPFSVETHPVLTSFGSALIATLFAYDGWINVGTLAGEMKNPGKMLPKVIIGGLSIVMAVYLLTNIAYLFVLDSSQLAGTDTPAALVASHLFEGIGSKLVTIGILISVFGGINGYIISGLRVPYALATQKMLPFSDWFARINPKTNLPINGGLVMLGIAIVMILTGQFNQLTDLIVFVIWFFITLTFIAVIILRKTQPDIERPYRVPFYPVIPLIAIIGGLYIIFNTLIVQPKNAFIGILLTLIGIPIYFY
# CKKKYGS
# >pro_600AA.B
# QVQLVESGGGVVQAGGSLRLSCAASGRTFSSRAMGWFRQAPGEGREFVATISWSGSYTEYADSVKGRVTISRDNAKNTVYLQMNSLKPGDTAVYHCAAKNGGAASNYPNDYVYWGQGTQVTVSSHHHHHHE"

# # 蛋白质-DNA复合物测试
# echo "Running protein-DNA complex test..."
# python $SCRIPT_PATH --protein ">pro_DNA.A
# ASSINPWILTGFADAEGSFGLYIINRNRGRIRYTTRLKFTITLHNKDKSILENIQSTWKVGI" --dna ">pro_DNA.B
# gggaatggcagtattcatccacaatg
# >pro_DNA.C
# ccattgtggatgaatactgccattcc"

# # 蛋白质-配体复合物测试
# echo "Running protein-ligand complex test..."
# python $SCRIPT_PATH --protein ">pro_lig.A
# ADLKAFSKHIYNAYLKNFNMTKKKARSILTGKASHTAPFVIHDIETLWQAEKGLVWKQLVNGLPPYKEISVHVFYRCQCTTVETVRELTEFAKSIPSFSSLFLNDQVTLLKYGVHEAIFAMLASIVNKDGLLVANGSGFVTREFLRSLRKPFSDIIEPKFEFAVKFNALELDDSDLALFIAAIIILCGDRPGLMNVPRVEAIQDTILRALEFHLQANHPDAQYLFPKLLQKMADLRQLVTEHAQMMQRIKKTETETSLHPLLQEIYKDMY" --ligand "CC(=O)OC1C[NH+]2CCC1CC2
# CCD,ATP,HY3"

# # 原有的简单测试
# echo "Running simple test..."
# python $SCRIPT_PATH --job_name complex --protein "MALWMRLLPLLALLALWGPDPAAA" --ensemble 5 --recycle 10